# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Set-ExecutionPolicy AllSigned -Scope Process -Force
                iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
                srcclr scan --url https://github.com/srcclr/example-ruby
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      http --auth-type=veracode_hmac "https://api.veracode.com/appsec/v1/applications?name={applicationName}"
      
      http --auth-type=veracode_hmac "https://api.veracode.com/srcclr/sbom/v1/targets/{applicationGuid}/cyclonedx?type=application"
          
         
